////////////////////////////////////////////////////////////////////////////////
//                 Mason SRCT: FlopStream Main App Routes
// - This routing file describes the main front-end's routing.
// - This serves the root page as well as parses preset url's generated by the
//   application
////////////////////////////////////////////////////////////////////////////////
var express = require('express');
var router = express.Router();

// Load site wide configurations
var config = require('../config');

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { config });
})

router.post('/upload', function(req, res) {
    var sampleFile;

    if (!req.files) {
        res.redirect('/404');
        return;
    }

    sampleFile = req.files.sampleFile;
    sampleFile.mv(config.saveLocation, function(err) {
        if (err) {
            res.redirect('/500');
        }
        else {
            config.onePage.stepOne = false;
            config.onePage.stepTwo = true;
            config.onePage.stepThree = false;

            res.redirect('/');
            return;
        }
    });
});

router.post('/upload2', function(req, res) {
    config.onePage.stepOne = false;
    config.onePage.stepTwo = false;
    config.onePage.stepThree = true;

    res.redirect('/');
    return;
})

module.exports = router;
